>PROJ_ROOT := ..
CXX := g++
CXXFLAGS := -std=c++11 -O3 -Wall -Wextra -Wno-unused-parameter -fPIC
LDFLAGS := -L$(PROJ_ROOT)/librariesLinux -Wl,-rpath,'$$ORIGIN'
LIBS := -lfaust -lrtaudio
TARGET := $(PROJ_ROOT)/librariesLinux/libdynamic-engine.so

SRC := $(PROJ_ROOT)/architecture/faust/dsp/faust-dynamic-engine_noMIDI.cpp

INC_FLAGS := -I$(PROJ_ROOT)/architecture \
-I$(PROJ_ROOT)/architecture/faust \
-I$(PROJ_ROOT)/architecture/faust/dsp \
-I$(PROJ_ROOT)/architecture/faust/audio \
-I$(PROJ_ROOT)/compiler/interpreter

DEFINES := -DINTERP_DSP -DRTAUDIO_DRIVER -DSOUNDFILE -DDAISY

# Build Target
$(TARGET): $(SRC)
	@mkdir -p $(dir $(TARGET))
	$(CXX) $(CXXFLAGS) $(INC_FLAGS) $(DEFINES) $< $(LDFLAGS) $(LIBS) -shared -o $@

# Clean target
clean:
	rm -f $(TARGET)

.PHONY: clean

