name: MacOS

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      # Check out the repository using the latest stable version
      - uses: actions/checkout@v4

      # Build Faust (or any project-specific build step)
      - name: Build Faust
        run: make all
