name: MacOS

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs the workflow on pull requests to the `master-dev` branch
  pull_request:
    branches: [master-dev]

jobs:
  build:
   
    runs-on: macos-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Build Faust (or any project-specific build step)
      - name: Build Faust
        run: make

