name: MacOS

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows you to run this workflow on pull requests to master-dev
  pull_request:
    branches: [master-dev]

jobs:
  build:
    # Ensure the job runs only if the repository owner is 'grame-cncm' or it's a pull request
    if: github.repository_owner == 'grame-cncm' || github.event_name == 'pull_request'
    runs-on: macos-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Build Faust (or any project-specific build step)
      - name: Build Faust
        run: make

      # Upload the built binary as an artifact
