name: Ubuntu

on:
  workflow_dispatch:

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y libmicrohttpd-dev llvm-14 llvm-14-dev

    - name: Add LLVM to PATH
      run: echo "/usr/lib/llvm-14/bin" >> $GITHUB_PATH

    - name: Build Faust
      run: make all
