name: Windows

on:
 
  workflow_dispatch:

jobs:
  build:
   
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
  
    - name: Get latest CMake and ninja
      uses: lukka/get-cmake@latest

    - name: Build Faust
      run: |
        make -C build cmake BACKENDS=all.cmake TARGETS=win-all.cmake
        make -C build
