name: Windows

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      run-tests:
        description: 'Run tests'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Build Faust
        run: |
      
      - name: Upload Faust Artifacts
        uses: actions/upload-artifact@v4
        with:
           name: faust-windows-build
           path: build/
  
