name: Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
  
    - name: Get latest CMake and ninja
      uses: lukka/get-cmake@latest

    - name: Build Faust
      run: |
        make -C build cmake BACKENDS=regular.cmake TARGETS=win-ci.cmake
        make -C build
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: faust-build-output
        path: |
          build/**/*.dll
          build/**/*.exe
          build/**/*.lib
        if-no-files-found: error
