name: Build on Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up make
      run: choco install make
      shell: powershell

    - name: Run make all
      run: make all
